config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get 'profile', to: 'static_pages#profile'

  resources :exams do 
    collection do
      get :random
      post :random, to: 'exams#create_random'
      get :find_question, to: 'questions#find_question'
      get :search
    end

    member do
      get :submit
      post :sunmit, to: 'results#create'
    end
  end

  resources :questions do
  end
  
  resources :results, only: [:show, :create, :destroy] do
    collection do
      get :mysubmitted
      get :top
    end
  end

  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/"
  end

  get '/users', to: 'users#show_all'
  delete '/users/:id/delete', to: 'users#destroy'

  # get "*path" => redirect("/")
end

app/views/layouts/base/admin/_header.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
<!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to "Home", root_path, class: "nav-link"%>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to "Contact", contact_path, class: "nav-link" %>
    </li>
  </ul>

  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item dropdown dropleft">
        <a class="nav-link" data-bs-toggle="dropdown" href="/profile" aria-haspopup="true" aria-expanded="false">
          <i class="far fa-user mr-1"></i><%= current_user.email %>
        </a>
        <div class="dropdown-menu dropdown-menu-sm">
          <div class="dropdown-item">
            <i class="fas fa-id-badge"></i><%= link_to "Profile", profile_path, class: "dropdown-item d-inline"%>
          </div>
          <div class="dropdown-divider"></div>
          <div class="dropdown-item">
            <i class="fas fa-cog"></i><%= link_to "Setting", edit_user_registration_path(current_user), class: "dropdown-item d-inline" %>
          </div>
          <div class="dropdown-divider"></div>
          <div class="dropdown-item">
          <i class="fas fa-sign-out-alt"></i><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item d-inline"%>
          </div>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
          <%= link_to "Sign In", signin_path, class: 'btn btn-outline-info mr-2' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up",new_user_registration_path, class: 'btn btn-outline-success' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/base/admin/_slidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <div class="sidebar">
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">       
        <li class="nav-item">
          <div class="nav-link" id="all-exam">
          <i class="fas fa-pencil-ruler"></i>
          <%= link_to "All Exam", exams_path, class: 'd-inline' %>
          </div>
        </li>
        <li class="nav-item" >
          <div class="nav-link" id="create-exam">
            <i class="fas fa-pencil-ruler"></i>
            <%= link_to "Create Exam", new_exam_path, class: 'd-inline' %>
          </div>
        </li>
        <li class="nav-item" >
          <div class="nav-link" id="all-question">
            <i class="fas fa-question" ></i>
            <%= link_to "All Question", questions_path, class: 'd-inline' %>
          </div>
        </li>
        <li class="nav-item" >
          <div class="nav-link" id="create-question">
            <i class="fas fa-question"></i>
            <%= link_to "Create Question", new_question_path, class: 'd-inline' %>
          </div>
        </li>

        <li class="nav-item" >
          <div class="nav-link" id="show-all">
          <i class="fas fa-users"></i>
          <%= link_to "All User", users_path, class: 'd-inline' %>
          </div>
        </li>

        <li class="nav-item" >
          <div class="nav-link" id="top-results">
            <i class="fas fa-chart-line"></i>
            <%= link_to "Top", top_results_path, class: 'd-inline' %>
          </div>
        </li>
      </ul>
    </nav>
  </div>
</aside>