config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get 'profile', to: 'static_pages#profile'

  resources :exams do 
    collection do
      get :random
      post :random, to: 'exams#create_random'
      get :find_question, to: 'questions#find_question'
      get :search
    end

    member do
      get :submit
      post :sunmit, to: 'results#create'
    end
  end

  resources :questions do
  end
  
  resources :results, only: [:show, :create, :destroy] do
    collection do
      get :mysubmitted
      get :top
    end
  end

  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/"
  end

  get '/users', to: 'users#show_all'
  delete '/users/:id/delete', to: 'users#destroy'

  # get "*path" => redirect("/")
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    attr_accessor :remember_token
    has_many :exams, dependent: :destroy
    has_many :results, dependent: :nullify
    belongs_to :school, optional: true

    # validates :name, presence: true
    validates :password, presence: true, confirmation: true,
                            length: { minimum: 6 }
    validates :email, presence:true, uniqueness: true


    def admin?
        admin_role?
    end

    def results_average
        result_count = results.count > 0 ? results.count : 1
        results.sum(:value) / result_count
    end

    def submitted
        results.count
    end

    scope :top_user, ->{ joins(:results).order("results.value").group(:id) }
    scope :user, ->{ where(admin_role: false) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def destroy
    user = User.find(params[:format])
    authorize! :destroy, user
    if user.destroy!
      flash[:success] = 'Delete User Success!'
    else
      flash[:danger] = 'Delete User Fails!'
    end
    @users = User.user.page(params[:page]).per(10)
    redirect_to users_path
  end

  def show_all
    authorize! :destroy, @user
    if params[:format]
      @user = User.find(params[:format])
      @results = @user.results
      render 'detail'
    end
    @users = User.user.page(params[:page]).per(10)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/detail.html.erb
<div class="card" id="search-results">
  <div class="card-header">
    <h3 class="card-title">Exam</h3>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Submitted</th>
          <th>Result Average</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%=  %></td>
          <td><%= @user.name %></td>
          <td><%= @user.email %></td>
          <td><%= @user.submitted %></td>
          <td><%= @user.results_average %></td>
          <td><%= link_to "Delete", users_delete_path(@user) ,data: { confirm: 'Are you sure?' }, method: :post, class: 'btn btn-sm btn-danger btn-flat pull-left btn-add' %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="card" id="search-results">
  <div class="card-header">
    <h3 class="card-title">Submitted</h3>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Exam Name</th>
          <th>Grade</th>
          <th>Time</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @results.each do |result| %>
          <tr>
            <td><%=  %></td>
            <td><% if result.exam_name != "Deleted" %><%= link_to "#{result.exam_name}", results_path(result) %><% else %>Deleted<% end %></td>
            <td><%= result.value %></td>
            <td><%= show_minutes_seconds(result.time) %></td>
            <td><%= result.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show_all.html.erb
<div class="card" id="search-results">
  <div class="card-header">
    <h3 class="card-title">Exam</h3>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Submitted</th>
          <th>Result Average</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each.with_index(1) do |user, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= user.name %></td>
          <td><%= link_to user.email, users_path(user) %></td>
          <td><%= user.submitted %></td>
          <td><%= user. results_average %></td>
          <td><%= link_to "Delete", users_path(user) ,data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sm btn-danger btn-flat pull-left btn-add' %></td>
        </tr>
        <% end %>
        <%= paginate @users %>
      </tbody>
    </table>
  </div>
</div>
<script>
    $('#user-list a').addClass('active')
</script>