config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get 'profile', to: 'static_pages#profile'

  resources :exams do 
    collection do
      get :random
      post :random, to: 'exams#create_random'
      get :find_question, to: 'questions#find_question'
      get :search
    end

    member do
      get :submit
      post :sunmit, to: 'results#create'
    end
  end

  resources :questions do
  end
  
  resources :results, only: [:show, :create, :destroy] do
    collection do
      get :mysubmitted
      get :top
    end
  end

  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/"
  end

  get '/users', to: 'users#show_all'
  delete '/users/:id/delete', to: 'users#destroy'

  # get "*path" => redirect("/")
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    attr_accessor :remember_token
    has_many :exams, dependent: :destroy
    has_many :results, dependent: :nullify
    belongs_to :school, optional: true

    # validates :name, presence: true
    validates :password, presence: true, confirmation: true,
                            length: { minimum: 6 }
    validates :email, presence:true, uniqueness: true


    def admin?
        admin_role?
    end

    def results_average
        result_count = results.count > 0 ? results.count : 1
        results.sum(:value) / result_count
    end

    def submitted
        results.count
    end

    scope :top_user, ->{ joins(:results).order("results.value").group(:id) }
    scope :user, ->{ where(admin_role: false) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def destroy
    user = User.find(params[:format])
    authorize! :destroy, user
    if user.destroy!
      flash[:success] = 'Delete User Success!'
    else
      flash[:danger] = 'Delete User Fails!'
    end
    @users = User.user.page(params[:page]).per(10)
    redirect_to users_path
  end

  def show_all
    authorize! :destroy, @user
    if params[:format]
      @user = User.find(params[:format])
      @results = @user.results
      render 'detail'
    end
    @users = User.user.page(params[:page]).per(10)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/base/user/_navbar.html.erb
<style>
.topnav a:hover {
    border-bottom: 3px solid red;
}

nav {
  margin-bottom: 50px;
  border-radius: 10px;  
} 
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-warning" id="user-nav">
  <a class="navbar-brand" href="/">Exam App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto topnav">
      <li class="nav-item active">
        <%= link_to "All Exams", exams_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to "Random Exam", random_exams_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to "Top", top_results_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to "My Submit", mysubmitted_results_path, class: 'nav-link' %>
      </li>
      <% unless  user_signed_in? %>
        <li class="nav-item">
            <a class="nav-link btn btn-primary text-white me-2" type="button" href="/users/sign_in" data-toggle="modal" data-target="#myModal">Sign In</a>                  
        </li>
        <li class="nav-item">
            <a class="nav-link btn btn-danger text-white" type="button" href="/users/sign_up" data-toggle="modal" data-target="#myModal">Register</a>
        </li>
      <% else %>
        <li class="nav-item dropdown dropleft">
          <a class="nav-link" data-bs-toggle="dropdown" href="/profile" aria-haspopup="true" aria-expanded="false">
            <i class="far fa-user mr-1"></i><%= current_user.name %>
          </a>
          <div class="dropdown-menu dropdown-menu-sm">
            <div class="dropdown-item">
            <i class="fas fa-id-badge"></i><%= link_to "Profile", profile_path, class: "dropdown-item d-inline"%>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
            <i class="fas fa-cog"></i><%= link_to "Setting", edit_user_registration_path(current_user), class: "dropdown-item d-inline" %>
            </div>
            <div class="dropdown-divider"></div>
            <div class="dropdown-item">
              <i class="fas fa-sign-out-alt"></i><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item d-inline"%>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/base/user/_slidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">

<div class="sidebar">
  <nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      
      <li class="nav-item has-treeview" id="exam-treeview">
        <a href="#" class="nav-link">
          <i class="fas fa-chart-bar"></i>
          <p>
            Exam
            <i class="right fas fa-angle-left"></i>
          </p>
        </a>
        <ul class="nav nav-treeview" >
          <li class="nav-item" id="all">
            <div class="nav-link" id="all-exam">
              <i class="far fa-circle nav-icon"></i>
              <%= link_to "All", exams_path %>
            </div>
          </li>
          <li class="nav-item" >
            <div class="nav-link" id="random-exam">
              <i class="far fa-circle nav-icon"></i>
              <%= link_to "Random Exam", random_exams_path %>
            </div>
          </li>
        </ul>
      </li>

      <li class="nav-item" >
        <div class="nav-link" id='my-submitted'>
          <i class="fab fa-algolia"></i>
          <%= link_to 'My Submitted', mysubmitted_results_path, class: 'd-inline' %>
        </div>
      </li>

      <li class="nav-item" >
        <div class="nav-link" id='top-results' >
          <i class="fas fa-chart-line"></i>
          <%= link_to 'Top', top_results_path, class: 'd-inline' %>
        </div>
      </li>

    </ul>
  </nav>
</div>
</aside>
<script>
</script>