config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get 'profile', to: 'static_pages#profile'

  resources :exams do 
    collection do
      get :random
      post :random, to: 'exams#create_random'
      get :find_question, to: 'questions#find_question'
      get :search
    end

    member do
      get :submit
      post :sunmit, to: 'results#create'
    end
  end

  resources :questions do
  end
  
  resources :results, only: [:show, :create, :destroy] do
    collection do
      get :mysubmitted
      get :top
    end
  end

  devise_for :users
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/"
  end

  get '/users', to: 'users#show_all'
  delete '/users/:id/delete', to: 'users#destroy'

  # get "*path" => redirect("/")
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :user, optional: true
  has_many :exam_questions, dependent: :delete_all
  has_many :questions, through: :exam_questions
  has_many :results, dependent: :nullify

  before_save :set_subject

  attribute :result_average, :integer, default: 0

  validates :user_id, presence: true

  def result_average
    result_count = results.count > 0 ? results.count : 1
    results.sum(:value) / result_count
  end

  def time_average
    result_count = results.count > 0 ? results.count : 1
    results.sum(:time) / result_count
  end

  def point_per_question(max)
    total_questions = questions.count
    max / total_questions
  end

  def total_results
    results.count
  end

  def subject_name
    subject_id.nil? ? "Undefine" : Subject.find(subject_id).name
  end

  def set_subject
    subject_id = questions.group(:subject_id).count.length == 1 ? questions.first.subject_id : 1
  end

  def exam_question_id(question)
    exam_questions.where(question_id: question.id).first.id
  end

  scope :search_by_name, ->(search) { where("name LIKE ?", "%#{search}%") }
  scope :search_by_time, ->(time) { where("time = ?", time) }
  scope :search_by_subject, ->(id) { where subject_id: id }
  scope :search_by_questions, ->(questions) { joins(:questions).group("exams.id").having("COUNT(questions.id) = ?", questions) }
end

app/controllers/exams_controller.rb
# frozen_string_literal: false

# exam controller
class ExamsController < ApplicationController
  def new
    @exam = current_user.exams.new
    authorize! :create, @exam
    @questions = Question.limit(20).pluck(:content, :id)
    @subject = Subject.all.map { |sb| [sb.name, sb.id] }
  end

  def create
    @exam = current_user.exams.new(name: params[:exam][:name], time: params[:exam][:time].to_i)
    authorize! :create, @exam
    question_id = params[:questions]
    if @exam.save!
      @exam.questions << Question.find_by(id: question_id)
      flash[:success] = 'Create Exam Success'
      redirect_to edit_exam_path(@exam)
    else
      flash[:danger] = 'Create Exam Fails'
      redirect_to exams_path
    end
  end

  def update
    @exam = Exam.find(params[:id])
    authorize! :create, @exam
    question_ids = params[:questions]
    if @exam.update!(name: params[:exam][:name], time: params[:exam][:time].to_i)
      question_ids.each do |question_id|
        @exam.questions << Question.find(question_id) unless @exam.questions.find(question_id)
      end
      flash[:success] = 'Update Exam Success'
      redirect_to exam_path
    else
      flash[:danger] = 'Update Exam Fails'
      redirect_to exam_path(@exam)
    end
  end

  def search
    @exams = Exam.page(params[:page]).per(10)
    if params[:search] || params[:time] || params[:questions] || params[:subject]
      @exams = Exam.search_by_name(params[:search]).page(params[:page]).per(8)
      @exams = @exams.search_by_questions(params[:questions].to_i) unless params[:questions].blank?
      @exams = @exams.search_by_subject(params[:subject].to_i) unless params[:subject].blank?
      @exams = @exams.search_by_time(params[:time].to_i) unless params[:time].blank?
      respond_to do |format|
        format.html {}
        format.js {}
      end
    end
  end

  def index
    @subjects = Subject.all.map { |subject| [subject.name, subject.id] }
    return @exams = Exam.all.page(params[:page]).per(9) unless current_user.admin?
    @exams = current_user.exams.page(params[:page]).per(9)
  end
  
  def show
    @exam = Exam.find(params[:id])
    @questions = @exam.questions
  end

  def submit
    @exam = Exam.find(params[:id])
    @questions = @exam.questions
    @result = Result.new
    @result.user_answers.build
  end

  def edit
    authorize! :update, @exam
    @subject = Subject.all.map { |sb| [sb.name, sb.id] }
    @exam = current_user.exams.find(params[:id])
    @questions = Question.limit(20).pluck(:content, :id)
  end

  def random
    @subject = Subject.all.map { |sb| [sb.name.capitalize, sb.id] }
  end
  
  def create_random
    time = params_or_random(params[:time], [15, 30, 45, 60, 90]) * 60
    questions = params_or_random(params[:questions], [5, 10, 15])
    subject = params[:subject].to_i
    question_type = params[:question_type].to_i
    @questions = Question.all
    @questions = @questions.group_by_subject(subject) if subject != 0
    @questions = @questions.group_by_type(question_type) if question_type != 0
    @questions = @questions.order(Arel.sql('RANDOM()')).limit(questions)
    @exam = current_user.exams.build(time: time, name: "Random (#{current_user.name})", subject_id: 1)
    authorize! :create, @exam
    if @exam.save!
      @exam.questions << @questions
      redirect_to exam_path(@exam)
    else
      redirect_to root_path
      flash[:warning] = 'Create Random Exam Fails'
    end
  end

  def destroy
    exam = Exam.find(params[:id])
    exam.destroy! ? flash[:success] = 'Delete Exam Success' : flash[:danger] = 'Delete Exam Fails'
    redirect_to exams_path
  end

  private
  
  def params_or_random(params, array)
    params = params.to_i
    params = array.sample if params.zero?
    params
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
    def show_time_exam(seconds)
        "#{seconds/60}m"
    end

    def time_exam
        [["15m", 15*60], ["30m", 30*60], ["45m", 45*60], ["60m", 60*60], ["90m", 90*60]]
    end
end

app/views/exams/_results.html.erb
<div class="card-header">
<h3 class="card-title">Exam</h3>
</div>
<div class="row">
<% @exams.each_with_index do |exam, index| %>
  <div class="col-md-4">
    <div class="card card-widget widget-user-2 shadow-sm">
      <div class="widget-user-header bg-warning">
        <h3 class="widget-user-username"><%= link_to "#{exam.name}", exam_path(exam) %></h3>
        <h5 class="widget-user-desc"><%= exam.subject_name.capitalize %></h5>
      </div>
      <div class="card-footer p-0">
        <ul class="nav flex-column">
          <li class="nav-item">
            <div  class="nav-link">
            Questions <span class="float-right badge bg-primary"><%= exam.questions.count %></span>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
            Time<span class="float-right badge bg-info"><%= show_time_exam exam.time %></span>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
            Submitted <span class="float-right badge bg-success"><%= exam.total_results %></span>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
            Average <span class="float-right badge bg-warning"><%= exam.result_average %></span>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @exams, theme: 'twitter-bootstrap-3' %>  
</div>

app/views/exams/edit.html.erb
<div class="card" id="search-results">
  <div>
    <%= form_for @exam do |f| %>
      <div class="box-body">          
        <%= f.label :"Name:", class: "col-sm-2" %>
        <%= f.text_field :name,  class: "form-control col-sm-9 ms-2 mb-2 d-inline", required: "required" %>
        <br />
        <%= f.label "time:", class: "col-sm-2" %>
        <%= f.select :time, options_for_select(time_exam), {}, class: 'form-select col-sm-2 ms-2 mb-2 d-inline', required: "required" %>
        <br />
        <%= f.label "Questions:", class: "col-sm-2" %>
        <div class="ms-2 d-inline h-4">
          <%= select_tag :questions, options_for_select(@questions, selected: f.object.questions.ids), {class: 'js-example-basic-multiple col-sm-6',name: "questions[]", multiple: "multiple"} %>
        </div>
      </div>
      <div class="box-footer clearfix">
        <%= f.submit "Update Exam", class: "btn btn-sm btn-info btn-flat pull-left btn-add mt-4 mb-2 ms-2 " %>
        <%= link_to "Delete Exam", exam_path(@exam) , data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-sm btn-danger btn-flat pull-left btn-add mt-3' %>
        <%= link_to "Try Start", exam_path(@exam), class: 'btn btn-sm btn-primary btn-flat pull-left btn-add mt-3' %>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('.js-example-basic-multiple').select2({
      placeholder: "Select a question",
      require: "required", 
      ajax:{
        url: 'exam/find_question',
        dataType: 'json',
        data: function(params){
          var questionID = $(this).val();
          return { search_content: params.term, selected_question_id: questionID }
        },
        processResults: function(data){
          return { results: data.results};
        },
      },
      templateResult: formatResult,
  
    }).trigger('change');
  
    function formatResult(question) {
      return question.content;
    }
    
    function formatSelection(question) {
      return question.content || question.text;
    }
  
  });
</script>

app/views/exams/index.html.erb
<div>
    <%= form_tag(search_exams_path, method: "get", remote: true, class: "ms-2") do %>
        <%= label_tag "name:"%>
        <%= text_field_tag :search, params[:search], class: 'form-control col-sm-4 d-inline', placeholder: "Enter search term" %>
        <%= label_tag "time:"%>
        <%= select_tag :time, options_for_select(time_exam), class: 'form-select col-sm-1 d-inline', include_blank: true %>
        <%= label_tag "subject:"%>
        <%= select_tag :subject, options_for_select(@subjects), class: 'form-select col-sm-2 d-inline', include_blank: true  %>
        <%= label_tag "questions:"%>
        <%= select_tag :questions, options_for_select([[""],["5",5],["10",10],["15",20]]), class: 'form-select col-sm-1 d-inline' %>
        <%= submit_tag "Search", class: 'btn btn-primary d-block' %>
    <% end %>
</div>

<div class="card" id="search-results">
  <div class="card-header">
    <h3 class="card-title">Exam</h3>
  </div>
  <div class="row">
    <% @exams.each do |exam| %>
      <div class="col-md-4">
        <div class="card card-widget widget-user-2 shadow-sm">
          <div class="widget-user-header bg-warning">
            <h3 class="widget-user-username">
              <%if current_user.admin? %><%= link_to "#{exam.name}", edit_exam_path(exam) %>
              <% else %><%= link_to "#{exam.name}", exam_path(exam)%><% end %>
            </h3>
            <h5 class="widget-user-desc"><%= exam.subject_name.capitalize %></h5>
          </div>
          <div class="card-footer p-0">
            <ul class="nav flex-column">
              <li class="nav-item">
                <div  class="nav-link">
                Questions <span class="float-right badge bg-primary"><%= exam.questions.count %></span>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link">
                Time<span class="float-right badge bg-info"><%= show_time_exam exam.time %></span>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link">
                Submitted <span class="float-right badge bg-success"><%= exam.total_results %></span>
                </div>
              </li>
              <li class="nav-item">
                <div class="nav-link">
                Average <span class="float-right badge bg-warning"><%= exam.result_average %></span>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @exams, theme: 'twitter-bootstrap-3' %>  
  </div>
</div>

app/views/exams/new.html.erb
<div class="row">
  <div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Create Exam</h3>
    </div>
    <%= form_for @exam do |f| %>
      <div class="box-body">          
        <%= f.label :"Name:", class: "col-sm-1" %>
        <%= f.text_field :name,  class: "form-control col-sm-10 ms-2 mb-2 d-inline", required: "required" %>
        <br />
        <%= f.label "time:", class: "col-sm-1" %>
        <%= f.select :time, options_for_select(time_exam), {}, class: 'form-select col-sm-2 ms-2 mb-2 d-inline', required: "required" %>
        <br />
        <%= f.label "Questions:", class: "col-sm-1" %>
        <div class="ms-2 d-inline h-4">
          <%= select_tag :questions, options_for_select(@questions, selected: f.object.questions.ids), {class: 'js-example-basic-multiple col-sm-10 d-inline',name: "questions[]", multiple: "multiple"} %>
        </div>
      </div>
      <div class="box-footer clearfix">
        <%= f.submit "Create Exam", class: "btn btn-sm btn-info btn-flat pull-left btn-add mt-4" %>
      </div>
    <% end %>
  </div>
</div>
<script>
  $('#create-exam a').addClass('active')
  $(document).ready(function() {
    $('.js-example-basic-multiple').select2({
      placeholder: "Select a question",
      require: "required", 
      ajax:{
        url: '/exams/find_question',
        dataType: 'json',
        data: function(params){
          var questionID = $(this).val();
          return { search_content: params.term, selected_question_id: questionID }
        },
        processResults: function(data){
          return { results: data.results};
        },
      },
      templateResult: formatResult,
  
    }).trigger('change');
  
    function formatResult(question) {
      return question.content;
    }
    
    function formatSelection(question) {
      return question.content || question.text;
    }
  
  });
</script>

app/views/exams/random.html.erb
<style>

</style>

<div id="form-select">
    <%= form_tag do %>
        <div class='form-field'>
        <%= label_tag "time:", nil, class: "col-sm-2" %>
        <%= select_tag :time, options_for_select(time_exam), class: 'form-select col-sm-4 d-inline', include_blank: true %>
        </div>
        <%= label_tag "subject:", nil, class: "col-sm-2"%>
        <%= select_tag :subject, options_for_select(@subject), class: 'form-select col-sm-4 d-inline', include_blank: true %>
        <br />
        <%= label_tag "questions:", nil, class: "col-sm-2"%>
        <%= select_tag :questions, options_for_select([["5",5],["10",10],["15",15]]), class: 'form-select col-sm-4 d-inline', include_blank: true %>
        <br />
        <%= label_tag "type:", nil, class: "col-sm-2" %>
        <%= select_tag :question_type, options_for_select(type), class: 'form-select col-sm-4 d-inline', include_blank: true %>
        <%= submit_tag "Start", class: 'btn btn-primary d-block' %>
    <% end %>
</div>

app/views/exams/results.html.erb
<div class="card-header">
                <h3 class="card-title">Exam</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Questions</th>
                    <th>Time</th>
                    <th>Result</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @search_results_exams.each_with_index do |exam, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= exam.name %></td>
                    <td><%= exam.questions.count %></td>
                    <td><%= show_time_in_hour(exam.time) %></td>
                    <td><%= exam.result_average %></td>
                  </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>

app/views/exams/search.js.erb
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/exams/show.html.erb
</style>
<div class="card" id="search-results">
  <div class="card-header">
    <h3 class="card-title">Exam</h3>
  </div>
  <div class="card-body">
    <table class="table table-striped projects">
      <thead>
      </thead>
      <tbody>
        <tr><td><b>Name</b></td><td><%= @exam.name %></td></tr>
        <tr><td><b>Questions</b></td><td><%= @exam.questions.count %></td></tr>
        <tr><td><b>Subject</b></td><td><%= @exam.subject_name.capitalize %></td></tr>
        <tr><td><b>Time</b></td><td><%= show_time_exam(@exam.time) %></td></tr>
        <tr><td><b>Submitted</b></td><td><%= @exam.total_results %></td></tr>
        <tr><td><b>Result Average</b></td><td><%= @exam.result_average %></td></tr>
        <tr><td><b>Time Average</b></td><td><%= show_time_result(@exam.time_average) %></td></tr>
      </tbody>
    </table>
  </div>

  <div>
    <%= link_to "Start", submit_exam_path(@exam), class: 'btn btn-primary me-4 mb-1 float-sm-right' %>
  </div>
</div>

app/views/exams/submit.html.erb
<style>

</style>
<div class="card-body row" id="submit-page">
  <div id="submit-form">
    <%= form_for @result, url: results_path(@result) do |f| %>
      <%= f.hidden_field :subject_id, value: @exam.subject_id %>
      <%= f.hidden_field :exam_id, value: @exam.id %>
      <%= f.hidden_field :time, id:"current_time"%>
        <% @questions.each.with_index(1) do |question,index| %>
            <div class="question">
              <div class="question-content"><b><%= "Question #{index} : "%></b><br />
                <%= question.content %><br />
              </div>
              <div class="answers">
                  <% question.answers.each do |answer|%>
                      <%= f.fields_for :user_answers do |ff| %>
                        <%= ff.hidden_field :exam_question_id, value: @exam.exam_question_id(question) %>
                        <%= ff.hidden_field :answer_id, value: answer.id  %>
                        <% if question.types == 2 %>
                          <div class="answer-choice">
                            <%= ff.check_box(:correct)%>
                            <%= answer.content %>
                          </div>
                        <% else %>
                          <div class="answer-write">
                            <%= ff.text_field :content %>
                            <%= ff.hidden_field :answer_id, value: answer.id %>
                          </div>
                        <% end %>
                      <% end %>
                  <% end %>
              </div>
            </div>
          <% end %>
    <%= f.submit :Submit , id: "submit-form-button"%>
    <% end %>
  </div>
  <h3 class= "" id="time_count_down"></h3>
  <h3 class= "" id="answered"></h3>
</div>

<script>
  var countDownDate = new Date().getTime() + <%= @exam.time * 1000 %>;
  var questions = <%= @questions.count %>;
  var answereds = 0;
  var questionWrite = <%= @questions.group_by_type(1).count %>;
  var questionChoice = <%= @questions.group_by_type(2).count %>;
  document.getElementById("answered").innerHTML = "Answered : <br />" + answereds + " / " + questions;

  $('input[type= "text"]').change(function(){
      if (this.value != ""){
        answereds++;
      } 
      else{
        answereds--;
      }
    document.getElementById("answered").innerHTML = "Answered : <br />" + answereds + " / " + questions;
  });

  $('.answer-choice').click( function(){
    var children = $(this).parent().children('div').children('input[type="checkbox"]');
    questionChecked = false;
    userChecked = 0;
    for(var i = 0; i < children.length; i++){
      if(children[i].checked){
        userChecked ++;
      }
    }
    if(userChecked == 0){
      answereds++;
      document.getElementById("answered").innerHTML = "Answered : <br />" + answereds + " / " + questions; 
    }
    var check_box = $(this).children('input');
    var checked = check_box.prop('checked');
    if(checked && userChecked == 1){
      answereds--;
      document.getElementById("answered").innerHTML = "Answered : <br />" + answereds + " / " + questions; 
    }
    check_box.prop('checked', !checked);

  });

  var x = setInterval(function() {

    var now = new Date().getTime();
      
    var distance = countDownDate - now;
      
    var minutes = Math.floor(distance / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    var current_time = (<%= @exam.time * 1000 %> - distance)/1000;
      
    document.getElementById("time_count_down").innerHTML = "Time <br/>" + minutes + "m:" + seconds + "s ";

    document.getElementById("current_time").value = current_time;
      
    if (distance < 0) {    
      document.getElementById("submit-form").click();
    }
  }, 1000);





</script>